runtime: python27
api_version: 1
threadsafe: false

#instance_class: F2

env_variables:
        SENDGRID_API_KEY: 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

handlers:
        - url: /.*
          secure: always
          redirect_http_response_code: 301 
          script: TrackingSystem.wsgi.application

libraries:
        - name: django
          version: "1.11"

        - name: pycrypto
          version: "latest"

        - name: MySQLdb
          version: "latest"

        